version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: lynux_bot
    container_name: "LynuxBot"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
    restart: always
